version: '3'

services:
  app:
    build: .
    volumes:
      - ..:/app
      - bundle:/usr/local/bundle
      - tmp:/app/tmp
      - log:/app/log
    ports:
      - 3000:3000
    extra_hosts:
      localhost: "${DOCKER_HOST_IP}"
    environment:
      USER: "${USER}"
    env_file:
      - ../.env
    command: tail -f /dev/null

volumes:
  bundle:
  tmp:
  log:
